#version: "3.4"
services:
  petclinicRest:
    image: petclinic-rest:v1
    depends_on:
      - postgres
    ports:
      - "9966:9966"
    environment:
      - spring.profiles.active=postgres,spring-data-jpa
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
    networks:
      - petclinic

  petclinicWeb:
    image: petclinic-web:v1
    depends_on:
      - petclinicRest
    ports:
      - "4200:80"
    networks:
      - petclinic

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres-data:/var/lib/postgresql/data
#      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - petclinic

networks:
  petclinic:

volumes:
  postgres-data:

